# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0e0ebfe8f1440d4909342dc6730ecabacbb734e725297e57a975a82546812aed68f64f7d5aaff68dd4a85b06337022c0afad91cf1a6a482d480b8f07cd09dcc

test:
  secret_key_base: 2db07943f74482fdd76e101547f8662955fb7b67b425b40014a69438da5b32fffffaf78cd95c6aaf883a06ab91086d220206ea44784924aea291c63015c1b33a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
